# Data types

NumPy supports a much greater variety of numerical types than Python does.

The primitive types supported are tied closely to those in C.

NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics.Once you have imported NumPy using

In [1]:
import numpy as np

the dtypes are available as np.bool_, np.float32, np.int8 etc.

There are advanced types also known as Structured arrays.

There are 5 basic numerical types representing:

booleans (bool), integers (int), unsigned integers (uint), floating point (float) and complex. 

In [2]:
x=np.float32(1)
print(x)

y=np.int8(1.5)
print(y)

z=np.int_([1,2,3,4])
print(z)

1.0
1
[1 2 3 4]


To convert the type of array use astype() method

In [3]:
# z is an array of int32 type 
# int32 simply means Integer (-2147483648 to 2147483647)
print(z)
print(z.dtype)


# convert it to int16
z.astype(np.float16)

[1 2 3 4]
int32


array([1., 2., 3., 4.], dtype=float16)

#### Bools

np.bool : Boolean (True or False) stored as a byte

#### Integers

###### Signed

np.int8 : Byte (-128 to 127)

np.int16 : Integer (-32768 to 32767)

np.int32 : Integer (-2147483648 to 2147483647)

np.int64 : Integer (-9223372036854775808 to 9223372036854775807)



###### Unsigned

np.uint8 :Unsigned integer (0 to 255)

np.uint16 :Unsigned integer (0 to 65535)

np.uint32 :Unsigned integer (0 to 4294967295)

np.uint64 :Unsigned integer (0 to 18446744073709551615)

#### Floats

###### Half float

np.half / np.float16 : Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

###### Single precision

np.single / np.float32 : Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa

######  Double precision

np.double / np.float64 / np.float_ : Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa.

Note that this matches the precision of the builtin python float.

###### Extended precision

np.longdouble : Platform-defined extended-precision float

####  Complex

np.csingle / np.complex64 : Complex number, represented by two single-precision(32-bit) floats (real and imaginary components)

np.double / np.complex128 / np.complex_ : Complex number, represented by two single-precision(64-bit) floats (real and imaginary components)

Note that this matches the precision of the builtin python complex.

### Overflow errors in NumPy

NumPy numeric types have fixed sizes. This  may cause overflow errors when a value requires more memory than available in the data type.

For example, _*numpy.power*_ evaluates 100 * 10 ** 8 correctly for 64-bit integers, but gives 1874919424 (incorrect) for a 32-bit integer.

In [4]:
#int64 ranges to Integer (-9223372036854775808 to 9223372036854775807)
print(np.power(100,8, dtype=np.int64))

# int32 ranges to Integer (-2147483648 to 2147483647)
print(np.power(100,8,dtype=np.int32))

10000000000000000
1874919424


# Array Creation

### Conversion of other Python structures( e.g., lists, tuples) into NumPy Arrays

An array-like structure of python can be converted to NumPy array usint array() function.

In [5]:
x= np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# From list of different structurs
x= np.array([[1,2,3],[4,5,6],(7,8,9)])
print(x)
print(f"datatype is : {x.dtype}")
print(f"size is : {x.size}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
datatype is : int32
size is : 9


In [7]:
# From mix of different dtypes including ints, floats, and complex
x=np.array([1,2,3.0,4,5,6,2+3j,3.0])
print(x)
print(f"datatype is : {x.dtype}")
print(f"size is : {x.size}")

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 2.+3.j 3.+0.j]
datatype is : complex128
size is : 8


In [8]:
# From nested list

x=np.array([[1.,2],[3,4],[5,6]])
print(x)
print(f"datatype is : {x.dtype}")
print(f"size is : {x.size}")



[[1. 2.]
 [3. 4.]
 [5. 6.]]
datatype is : float64
size is : 6


# Intrinsic NumPy Array Creation

NumPy comes with some built-in functions for array creation:

###### np.zeros(shape, [dtype=float], [order='C'])

Return a new array of given shape(int or sequence of ints), type and order('C' for row-major order and 'F' for column-major order), filled with zeros.

In [9]:
# create array of 5-zeros

x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [11]:
#create array of 5-zeroes of type int

x=np.zeros(5,dtype=int)
print(x)

x=np.zeros((5,),dtype=int)
print(x)

#create array of zeroes of type complex and shape 2x3
x=np.zeros((2,3),dtype=np.csingle)
print(x)

[0 0 0 0 0]
[0 0 0 0 0]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


##### numpy.ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

In [12]:
x=np.ones((2,3),dtype=np.float16)
x

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

##### numpy.arange(([start, ]stop, [step, ]dtype=None)

arange() will create arrays with regularly incrementing values.

Return evenly spaced values within a given interval [start,stop)  i.e., interval including start but excluding stop.

stop : end of the range, this value is excluded. (Check the exceptional case when stop value is included in the range.)

For dtype=int, np.arange() and Python built-in function range() behaves similarly, only difference is the return type. numpy.arange() returns ndarray and range() returns a list.



In [19]:
# start at 0 and stop at 2 acc to [start,stop)
np.arange(3)

array([0, 1, 2])

In [20]:
# start=0 and stop value 3.0 i.e , float arguments
np.arange(3.0)

array([0., 1., 2.])

In [21]:
# [3,9)
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [22]:
# [3,9) and taking two steps forward
np.arange(3,9,2)

array([3, 5, 7])

In [26]:
# with non-integer step
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [50]:
np.linspace(5,50,5,True)

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])